name: Smart Deploy
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # Всегда создаем папку dist (даже пустую)
      - name: Ensure dist exists
        run: mkdir -p dist

      # Проверяем изменения
      - name: Check for resource changes
        id: check-resources
        run: |
          changed_files=$(git diff --name-only HEAD^ HEAD -- assets/ Components/)
          if [ -n "$changed_files" ]; then
            echo "needs_build=true" >> $GITHUB_OUTPUT
          else
            echo "✔ Нет изменений в ресурсах - пропускаем сборку"
          fi

      # Условная сборка
      - name: Build assets
        if: steps.check-resources.outputs.needs_build == 'true'
        run: |
          npm ci
          npm run build
          echo "Содержимое dist:" && ls -la dist/

      # Деплой с проверкой dist
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: 188.225.23.151
          username: snapget
          password: OO!VeL9j$6hq
          local-dir: ./
          server-dir: /test.snapget.ru/public_html/blog/wp-content/themes/flynt/
          exclude: |
            .git/
            node_modules/
            .github/
            dist/  # Исключаем, если пустая
          dangerous-clean-slate: false
        continue-on-error: true # Пропускаем ошибку, если dist пустой
