name: Smart Deploy
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Для сравнения с предыдущим коммитом

      # Проверяем изменения в assets/ И Components/
      - name: Check for resource changes
        id: check-resources
        run: |
          changed_files=$(git diff --name-only HEAD^ HEAD -- assets/ Components/)
          if [ -n "$changed_files" ]; then
            echo "needs_build=true" >> $GITHUB_OUTPUT
            echo "Changed files:" $changed_files
          fi

      # Сборка только при изменении ресурсов
      - name: Build assets
        if: steps.check-resources.outputs.needs_build == 'true'
        run: |
          npm ci
          npm run build
          echo "Содержимое dist:" && ls -la dist/

      # Деплой всего (корень + актуальный dist)
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: 188.225.23.151
          username: snapget
          password: OO!VeL9j$6hq
          local-dir: ./dist/
          server-dir: /test.snapget.ru/public_html/blog/wp-content/themes/flynt/dist/
          exclude: |
            .git/
            node_modules/
            .github/
            *.md
            webpack.config.js
            package*.json
          dangerous-clean-slate: false
