name: Lightning Deploy
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Установка только необходимых глобальных пакетов
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 2. Кэширование зависимостей (только для сборки)
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      # 3. Установка зависимостей (только для сборки)
      - name: Install deps
        run: |
          npm ci --no-audit --ignore-scripts
          npm cache clean --force

      # 4. Определение изменений
      - name: Detect changes
        id: changes
        run: |
          changed_assets=$(git diff --name-only HEAD^ HEAD -- assets/)
          changed_js=$(git diff --name-only HEAD^ HEAD -- 'Components/**/*.js')

          if [ -n "$changed_assets" ] || [ -n "$changed_js" ]; then
            echo "needs_build=true" >> $GITHUB_OUTPUT
            echo "BUILD REQUIRED"
          fi

      # 5. Сборка только при изменениях
      - name: Build assets
        if: steps.changes.outputs.needs_build == 'true'
        run: |
          npm run build:production
          echo "Dist content:"
          ls -la dist/

      # 6. Чистый деплой без node_modules
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: 188.225.23.151
          username: snapget
          password: OO!VeL9j$6hq
          local-dir: ./
          server-dir: /test.snapget.ru/public_html/blog/wp-content/themes/flynt/
          exclude: |
            .*
            node_modules/
            package*
            webpack*
            *.log
            *.md
          include: |
            ${{ steps.changes.outputs.all_changed_files }}
            dist/**
          dangerous-clean-slate: false
          verify: false
          git-sync: false
