name: Smart Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Для сравнения изменений между коммитами

      # 1. Установка зависимостей
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      # 2. Определение измененных файлов (кроме node_modules)
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **
            !node_modules/**
          files_ignore: |
            .git/**
            dist/**
            node_modules/**

      # 3. Сборка проекта (всегда)
      - name: Build project
        run: |
          npm run build
          echo "Содержимое dist:"
          ls -la dist/

      # 4. Деплой измененных файлов + dist
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 188.225.23.151
          username: snapget
          password: OO!VeL9j$6hq
          local-dir: ./
          server-dir: /test.snapget.ru/public_html/blog/wp-content/themes/flynt/
          include: |
            ${{ steps.changed-files.outputs.all_modified_files }}
            dist/**
          exclude: |
            .git/**
            .github/**
            node_modules/**
            *.log
            *.config.js
            *.lock
          dangerous-clean-slate: false
          log-level: verbose
