name: Build and Deploy
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: composer

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install PHP dependencies
        run: composer install --no-interaction

      - name: Install Node dependencies
        run: npm ci

      - name: Build theme
        run: npm run build:production

      - name: Verify dist contents
        run: ls -la dist/

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: 188.225.23.151
          username: snapget
          password: OO!VeL9j$6hq
          port: 21 # Явно укажите порт
          protocol: ftps # Попробуйте разные варианты: ftp, ftps, sftp
          local-dir: ./dist/
          server-dir: /public_html/blog/wp-content/themes/flynt/
          dangerous-clean-slate: false
          log-level: verbose
