name: Optimized Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # 1. Установка PHP (только для Flynt)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: composer
          coverage: none

      - name: Install PHP dependencies
        run: composer install --no-interaction --no-dev

      # 2. Установка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node dependencies
        run: npm ci

      # 3. Определение изменений в критичных папках
      - name: Check for relevant changes
        id: changes
        uses: tj-actions/changed-files@v35
        with:
          files: |
            assets/**
            Components/**/*.js

      # 4. Условная пересборка
      - name: Rebuild if needed
        if: steps.changes.outputs.any_changed == 'true'
        run: |
          echo "Обнаружены изменения - пересобираем проект"
          rm -rf dist/  # Удаляем старую сборку
          npm run build:production
          echo "Новое содержимое dist:"
          ls -la dist/

      # 5. Проверка существования dist
      - name: Ensure dist exists
        if: steps.changes.outputs.any_changed != 'true'
        run: |
          if [ ! -d "dist" ]; then
            echo "Папка dist отсутствует - собираем проект"
            npm run build:production
          else
            echo "Используем существующую папку dist"
          fi
          echo "Содержимое dist:"
          ls -la dist/

      # 6. Умный деплой
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 188.225.23.151
          username: snapget
          password: OO!VeL9j$6hq
          local-dir: ./
          server-dir: /test.snapget.ru/public_html/blog/wp-content/themes/flynt/
          include: |
            ${{ steps.changes.outputs.all_modified_files }}
            dist/**
          exclude: |
            .git/**
            .github/**
            node_modules/**
            vendor/**
            *.log
            *.config.js
            *.lock
          dangerous-clean-slate: false
          log-level: verbose
