name: Build and Deploy
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build theme
        run: npm run build # Собираем dist/ на GitHub

      - name: Upload to server via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: 188.225.23.151
          username: snapget
          password: OO!VeL9j$6hq
          local-dir: ./dist/ # Папка сборки
          server-dir: /test.snapget.ru/public_html/blog/wp-content/themes/flynt/
