name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for changes in assets or components
        id: changes
        uses: tj-actions/changed-files@v35
        with:
          files: |
            assets/**
            components/**/*.js

      - name: Set up Node.js
        if: steps.changes.outputs.any_changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        if: steps.changes.outputs.any_changed == 'true'
        run: npm install

      - name: Build dist
        if: steps.changes.outputs.any_changed == 'true'
        run: npm run build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: 188.225.23.151
          username: snapget
          password: OO!VeL9j$6hq
          local-dir: ./
          server-dir: /test.snapget.ru/public_html/blog/wp-content/themes/flynt/
          exclude: |
            .git/*
            .github/*
            node_modules/*
            src/*
            *.json
            *.lock
            *.md
            *.config.js
          dangerous-clean-slate: false
          log-level: verbose
