name: Smart Deploy
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Получаем текущий и предыдущий коммит

      # Надежная проверка изменений
      - name: Check for asset changes
        id: check-assets
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- assets/ Components/)
          else
            changed_files=$(git diff --name-only HEAD~1 HEAD -- assets/ Components/)
          fi

          if [ -n "$changed_files" ]; then
            echo "needs_build=true" >> $GITHUB_OUTPUT
            echo "Changed files: $changed_files"
          fi

      # Остальные шаги остаются без изменений
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Build assets
        if: steps.check-assets.outputs.needs_build == 'true'
        run: npm run build:production

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: 188.225.23.151
          username: snapget
          password: OO!VeL9j$6hq
          local-dir: ./
          server-dir: /test.snapget.ru/public_html/blog/wp-content/themes/flynt/
          exclude: |
            .git/
            node_modules/
            .github/
