name: Smart Deploy
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # Определяем изменения
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            assets/**
            Components/**/*.js
            Components/**/*.scss

      # Сборка при изменении ресурсов
      - name: Build assets
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          npm ci
          npm run build
          echo "Содержимое dist:"
          ls -la dist/

      # Деплой только нужных файлов
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4 # Используем последнюю версию
        with:
          server: 188.225.23.151
          username: snapget
          password: OO!VeL9j$6hq
          local-dir: ./dist/ # Указываем ТОЛЬКО папку dist
          server-dir: /test.snapget.ru/public_html/blog/wp-content/themes/flynt/
          exclude: |
            .git/
            .github/
            node_modules/
            *.log
            *.config.js
          dangerous-clean-slate: false
          log-level: verbose
