name: Guaranteed Dist Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # Установка зависимостей
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: composer

      - name: Install PHP dependencies
        run: composer install --no-interaction --no-dev

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node dependencies
        run: npm ci

      # Всегда собираем проект (убрали условие)
      - name: Build project
        run: |
          rm -rf dist/
          npm run build:production
          echo "Содержимое dist:"
          ls -la dist/

      # Деплой в ДВА этапа:
      # 1. Сначала заливаем ТОЛЬКО папку dist
      - name: Deploy Dist Folder
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 188.225.23.151
          username: snapget
          password: OO!VeL9j$6hq
          port: 21
          protocol: ftp
          local-dir: ./dist/
          server-dir: /test.snapget.ru/public_html/blog/wp-content/themes/flynt/dist/
          dangerous-clean-slate: true # Перезаписываем всю папку dist
          log-level: verbose

      # 2. Затем заливаем остальные измененные файлы
      - name: Deploy Other Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 188.225.23.151
          username: snapget
          password: OO!VeL9j$6hq
          port: 21
          protocol: ftp
          local-dir: ./
          server-dir: /test.snapget.ru/public_html/blog/wp-content/themes/flynt/
          exclude: |
            .git/**
            .github/**
            node_modules/**
            vendor/**
            dist/**  # Исключаем dist, так как уже залили
            *.log
            *.config.js
            *.lock
          dangerous-clean-slate: false
          log-level: verbose
