name: Optimized Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # Установка зависимостей
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: composer

      - name: Install PHP dependencies
        run: composer install --no-interaction --no-dev

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node dependencies
        run: npm ci

      # Определение изменений
      - name: Check for changes
        id: changes
        uses: tj-actions/changed-files@v35
        with:
          files: |
            assets/**
            Components/**/*.js
            *.php

      # Условная сборка
      - name: Build project
        if: steps.changes.outputs.any_changed == 'true'
        run: |
          rm -rf dist/
          npm run build:production
          echo "Build complete. Dist contents:"
          ls -la dist/

      # Основной деплой (используем корневую папку)
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 188.225.23.151
          username: snapget
          password: OO!VeL9j$6hq
          port: 21
          protocol: ftp
          local-dir: ./ # <-- Используем корневую папку проекта
          server-dir: /test.snapget.ru/public_html/blog/wp-content/themes/flynt/
          include: |
            ${{ steps.changes.outputs.all_modified_files }}
            dist/**
          exclude: |
            .git/**
            .github/**
            node_modules/**
            vendor/**
            *.log
            *.config.js
            *.lock
          dangerous-clean-slate: false
          log-level: verbose
